package org.code.api.services;

import java.util.UUID;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

/**
 * Persists post-commit deletion work and retries idempotent filesystem removal. Row locks allow
 * multiple application instances to claim disjoint batches.
 *
 * @author Enzo Ribas <a href="https://github.com/oEnzoRibas">@oEnzoRibas</a>
 */
@Service
public class AttachmentCleanupService {
  private final JdbcTemplate jdbc;
  private final StorageService storage;

  /**
   * Configures durable cleanup.
   *
   * @param jdbc transactional database access
   * @param storage persistent byte adapter
   */
  public AttachmentCleanupService(JdbcTemplate jdbc, StorageService storage) {
    this.jdbc = jdbc;
    this.storage = storage;
  }

  /**
   * Enqueues cleanup in the caller's metadata transaction.
   *
   * @param path path previously generated by the storage adapter
   */
  @Transactional(propagation = Propagation.MANDATORY)
  public void enqueue(String path) {
    jdbc.update(
        "INSERT INTO attachment_file_deletion(id, storage_path) VALUES (?, ?) ON"
            + " CONFLICT(storage_path) DO NOTHING",
        UUID.randomUUID(),
        path);
  }

  /** Processes up to ten committed jobs; failed deletions remain eligible for a later retry. */
  @Transactional
  public void processPending() {
    var jobs =
        jdbc.query(
            "SELECT id, storage_path FROM attachment_file_deletion WHERE next_attempt_at <="
                + " CURRENT_TIMESTAMP ORDER BY created_at LIMIT 10 FOR UPDATE SKIP LOCKED",
            (rs, row) -> new Job(rs.getObject(1, UUID.class), rs.getString(2)));
    for (Job job : jobs) {
      try {
        storage.delete(job.path());
      } catch (RuntimeException exception) {
        jdbc.update(
            "UPDATE attachment_file_deletion SET attempts = attempts + 1, next_attempt_at ="
                + " CURRENT_TIMESTAMP + INTERVAL '1 minute', last_error = 'Storage deletion failed;"
                + " retry scheduled' WHERE id = ?",
            job.id());
        continue;
      }
      jdbc.update("DELETE FROM attachment_file_deletion WHERE id = ?", job.id());
    }
  }

  /**
   * @param id cleanup job identity
   * @param path internal storage path
   */
  private record Job(UUID id, String path) {}
}
