services:
  database:
    container_name: irr_database
    image: postgres:16
    restart: always

    environment:
      POSTGRES_USER: irr_admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: irr
    volumes:
      # O SEGREDO ESTÁ AQUI: Salva os dados na sua máquina real
      - banco_dados_volume:/var/lib/postgresql/data
    ports:
      - "5435:5432"

  backend:
    container_name: irr_backend
    image: eclipse-temurin:21-jdk
    working_dir: /app
    volumes:
      - .:/app
      - backend_maven_cache:/root/.m2
    ports:
      - "8081:8081"
      - "5005:5005"
    depends_on:
      - database
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=irr
      - DB_USER=irr_admin
      - DB_PASSWORD=root
    command: ./mvnw spring-boot:run -Dspring-boot.run.jvmArguments="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"

volumes:
  backend_maven_cache:
  banco_dados_volume: 
