services:
  postgres:
    image: postgres:16
    container_name: irr_postgres
    restart: always
    environment:
      POSTGRES_USER: irr_admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-SuperSecurePass123}
      POSTGRES_DB: irr_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
