# ===================================================================
# Database ( docker ) configuration
# ===================================================================
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.host=${DB_HOST}

spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# spring security -> disable basic login screen
spring.security.user.name=admin
spring.security.user.password=admin

# JWT Configuration
rsa.publickey=classpath:public.key
rsa.privatekey=classpath:private.key

# debug + endpoint that shows all mapped endpoints for troubleshooting
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=DEBUG
management.endpoints.web.exposure.include=mappings

# ===================================================================
# JPA / Hibernate configuration
# ===================================================================
spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8081

# ===================================================================
# JPA / Hibernate configuration
# ===================================================================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migrations
spring.flyway.baseline-on-migrate=true
