-- Organization cutover: preserve unmapped history, never infer ownership from its actor.
-- Author: Enzo Ribas (https://github.com/oEnzoRibas)
ALTER TABLE material_category ADD COLUMN organization_id UUID REFERENCES organization(id) ON DELETE RESTRICT;
ALTER TABLE material_category ADD CONSTRAINT uq_material_category_scope UNIQUE (organization_id, id);
CREATE INDEX ix_material_category_organization ON material_category(organization_id);
ALTER TABLE material_type ADD COLUMN organization_id UUID REFERENCES organization(id) ON DELETE RESTRICT;
ALTER TABLE material_type ADD CONSTRAINT uq_material_type_scope UNIQUE (organization_id, id);
CREATE INDEX ix_material_type_organization ON material_type(organization_id);
ALTER TABLE material_subtype ADD COLUMN organization_id UUID REFERENCES organization(id) ON DELETE RESTRICT;
ALTER TABLE material_subtype ADD CONSTRAINT uq_material_subtype_scope UNIQUE (organization_id, id);
CREATE INDEX ix_material_subtype_organization ON material_subtype(organization_id);
ALTER TABLE attachment ADD COLUMN organization_id UUID REFERENCES organization(id) ON DELETE RESTRICT;
ALTER TABLE attachment ADD CONSTRAINT uq_attachment_scope UNIQUE (organization_id, id);
CREATE INDEX ix_attachment_organization ON attachment(organization_id);
ALTER TABLE vehicle ADD COLUMN organization_id UUID REFERENCES organization(id) ON DELETE RESTRICT;
ALTER TABLE vehicle ADD CONSTRAINT uq_vehicle_scope UNIQUE (organization_id, id);
CREATE INDEX ix_vehicle_organization ON vehicle(organization_id);
ALTER TABLE team_member ADD COLUMN organization_id UUID REFERENCES organization(id) ON DELETE RESTRICT;
ALTER TABLE team_member ADD CONSTRAINT uq_team_member_scope UNIQUE (organization_id, id);
CREATE INDEX ix_team_member_organization ON team_member(organization_id);
ALTER TABLE donor ADD COLUMN organization_id UUID REFERENCES organization(id) ON DELETE RESTRICT;
ALTER TABLE donor ADD CONSTRAINT uq_donor_scope UNIQUE (organization_id, id);
CREATE INDEX ix_donor_organization ON donor(organization_id);
ALTER TABLE collection ADD COLUMN organization_id UUID REFERENCES organization(id) ON DELETE RESTRICT;
ALTER TABLE collection ADD CONSTRAINT uq_collection_scope UNIQUE (organization_id, id);
CREATE INDEX ix_collection_organization ON collection(organization_id);
ALTER TABLE donation ADD COLUMN organization_id UUID REFERENCES organization(id) ON DELETE RESTRICT;
ALTER TABLE donation ADD CONSTRAINT uq_donation_scope UNIQUE (organization_id, id);
CREATE INDEX ix_donation_organization ON donation(organization_id);
ALTER TABLE input_item ADD COLUMN organization_id UUID REFERENCES organization(id) ON DELETE RESTRICT;
ALTER TABLE input_item ADD CONSTRAINT uq_input_item_scope UNIQUE (organization_id, id);
CREATE INDEX ix_input_item_organization ON input_item(organization_id);
ALTER TABLE buyer ADD COLUMN organization_id UUID REFERENCES organization(id) ON DELETE RESTRICT;
ALTER TABLE buyer ADD CONSTRAINT uq_buyer_scope UNIQUE (organization_id, id);
CREATE INDEX ix_buyer_organization ON buyer(organization_id);
ALTER TABLE sale ADD COLUMN organization_id UUID REFERENCES organization(id) ON DELETE RESTRICT;
ALTER TABLE sale ADD CONSTRAINT uq_sale_scope UNIQUE (organization_id, id);
CREATE INDEX ix_sale_organization ON sale(organization_id);
ALTER TABLE sale_item ADD COLUMN organization_id UUID REFERENCES organization(id) ON DELETE RESTRICT;
ALTER TABLE sale_item ADD CONSTRAINT uq_sale_item_scope UNIQUE (organization_id, id);
CREATE INDEX ix_sale_item_organization ON sale_item(organization_id);
ALTER TABLE inventory_log ADD COLUMN organization_id UUID REFERENCES organization(id) ON DELETE RESTRICT;
ALTER TABLE inventory_log ADD CONSTRAINT uq_inventory_log_scope UNIQUE (organization_id, id);
CREATE INDEX ix_inventory_log_organization ON inventory_log(organization_id);
ALTER TABLE sorting ADD COLUMN organization_id UUID REFERENCES organization(id) ON DELETE RESTRICT;
ALTER TABLE sorting ADD CONSTRAINT uq_sorting_scope UNIQUE (organization_id, id);
CREATE INDEX ix_sorting_organization ON sorting(organization_id);
ALTER TABLE sorted_item ADD COLUMN organization_id UUID REFERENCES organization(id) ON DELETE RESTRICT;
ALTER TABLE sorted_item ADD CONSTRAINT uq_sorted_item_scope UNIQUE (organization_id, id);
CREATE INDEX ix_sorted_item_organization ON sorted_item(organization_id);
ALTER TABLE pressing ADD COLUMN organization_id UUID REFERENCES organization(id) ON DELETE RESTRICT;
ALTER TABLE pressing ADD CONSTRAINT uq_pressing_scope UNIQUE (organization_id, id);
CREATE INDEX ix_pressing_organization ON pressing(organization_id);
ALTER TABLE pressed_bale ADD COLUMN organization_id UUID REFERENCES organization(id) ON DELETE RESTRICT;
ALTER TABLE pressed_bale ADD CONSTRAINT uq_pressed_bale_scope UNIQUE (organization_id, id);
CREATE INDEX ix_pressed_bale_organization ON pressed_bale(organization_id);
ALTER TABLE inventory_balance ADD COLUMN organization_id UUID REFERENCES organization(id) ON DELETE RESTRICT;
ALTER TABLE inventory_balance ADD CONSTRAINT uq_inventory_balance_scope UNIQUE (organization_id, id);
CREATE INDEX ix_inventory_balance_organization ON inventory_balance(organization_id);
ALTER TABLE material_type ADD CONSTRAINT fk_material_type_category_id_scope FOREIGN KEY (organization_id,category_id) REFERENCES material_category(organization_id,id) ON DELETE RESTRICT;
ALTER TABLE material_subtype ADD CONSTRAINT fk_material_subtype_type_id_scope FOREIGN KEY (organization_id,type_id) REFERENCES material_type(organization_id,id) ON DELETE RESTRICT;
ALTER TABLE collection ADD CONSTRAINT fk_collection_vehicle_id_scope FOREIGN KEY (organization_id,vehicle_id) REFERENCES vehicle(organization_id,id) ON DELETE RESTRICT;
ALTER TABLE collection ADD CONSTRAINT fk_collection_driver_id_scope FOREIGN KEY (organization_id,driver_id) REFERENCES team_member(organization_id,id) ON DELETE RESTRICT;
ALTER TABLE collection ADD CONSTRAINT fk_collection_mtr_generator_id_scope FOREIGN KEY (organization_id,mtr_generator_id) REFERENCES attachment(organization_id,id) ON DELETE RESTRICT;
ALTER TABLE collection ADD CONSTRAINT fk_collection_mtr_destinator_id_scope FOREIGN KEY (organization_id,mtr_destinator_id) REFERENCES attachment(organization_id,id) ON DELETE RESTRICT;
ALTER TABLE collection ADD CONSTRAINT fk_collection_collection_diary_id_scope FOREIGN KEY (organization_id,collection_diary_id) REFERENCES attachment(organization_id,id) ON DELETE RESTRICT;
ALTER TABLE donation ADD CONSTRAINT fk_donation_donor_id_scope FOREIGN KEY (organization_id,donor_id) REFERENCES donor(organization_id,id) ON DELETE RESTRICT;
ALTER TABLE donation ADD CONSTRAINT fk_donation_proof_attachment_id_scope FOREIGN KEY (organization_id,proof_attachment_id) REFERENCES attachment(organization_id,id) ON DELETE RESTRICT;
ALTER TABLE input_item ADD CONSTRAINT fk_input_item_collection_id_scope FOREIGN KEY (organization_id,collection_id) REFERENCES collection(organization_id,id) ON DELETE RESTRICT;
ALTER TABLE input_item ADD CONSTRAINT fk_input_item_donation_id_scope FOREIGN KEY (organization_id,donation_id) REFERENCES donation(organization_id,id) ON DELETE RESTRICT;
ALTER TABLE input_item ADD CONSTRAINT fk_input_item_material_subtype_id_scope FOREIGN KEY (organization_id,material_subtype_id) REFERENCES material_subtype(organization_id,id) ON DELETE RESTRICT;
ALTER TABLE sale ADD CONSTRAINT fk_sale_buyer_id_scope FOREIGN KEY (organization_id,buyer_id) REFERENCES buyer(organization_id,id) ON DELETE RESTRICT;
ALTER TABLE sale ADD CONSTRAINT fk_sale_nfe_attachment_id_scope FOREIGN KEY (organization_id,nfe_attachment_id) REFERENCES attachment(organization_id,id) ON DELETE RESTRICT;
ALTER TABLE sale ADD CONSTRAINT fk_sale_mtr_attachment_id_scope FOREIGN KEY (organization_id,mtr_attachment_id) REFERENCES attachment(organization_id,id) ON DELETE RESTRICT;
ALTER TABLE sale ADD CONSTRAINT fk_sale_cdf_attachment_id_scope FOREIGN KEY (organization_id,cdf_attachment_id) REFERENCES attachment(organization_id,id) ON DELETE RESTRICT;
ALTER TABLE sale_item ADD CONSTRAINT fk_sale_item_sale_id_scope FOREIGN KEY (organization_id,sale_id) REFERENCES sale(organization_id,id) ON DELETE RESTRICT;
ALTER TABLE sale_item ADD CONSTRAINT fk_sale_item_material_subtype_id_scope FOREIGN KEY (organization_id,material_subtype_id) REFERENCES material_subtype(organization_id,id) ON DELETE RESTRICT;
ALTER TABLE inventory_log ADD CONSTRAINT fk_inventory_log_material_subtype_id_scope FOREIGN KEY (organization_id,material_subtype_id) REFERENCES material_subtype(organization_id,id) ON DELETE RESTRICT;
ALTER TABLE sorted_item ADD CONSTRAINT fk_sorted_item_sorting_id_scope FOREIGN KEY (organization_id,sorting_id) REFERENCES sorting(organization_id,id) ON DELETE RESTRICT;
ALTER TABLE sorted_item ADD CONSTRAINT fk_sorted_item_input_item_id_scope FOREIGN KEY (organization_id,input_item_id) REFERENCES input_item(organization_id,id) ON DELETE RESTRICT;
ALTER TABLE sorted_item ADD CONSTRAINT fk_sorted_item_material_subtype_id_scope FOREIGN KEY (organization_id,material_subtype_id) REFERENCES material_subtype(organization_id,id) ON DELETE RESTRICT;
ALTER TABLE pressed_bale ADD CONSTRAINT fk_pressed_bale_pressing_id_scope FOREIGN KEY (organization_id,pressing_id) REFERENCES pressing(organization_id,id) ON DELETE RESTRICT;
ALTER TABLE pressed_bale ADD CONSTRAINT fk_pressed_bale_sorted_item_id_scope FOREIGN KEY (organization_id,sorted_item_id) REFERENCES sorted_item(organization_id,id) ON DELETE RESTRICT;
ALTER TABLE pressed_bale ADD CONSTRAINT fk_pressed_bale_material_subtype_id_scope FOREIGN KEY (organization_id,material_subtype_id) REFERENCES material_subtype(organization_id,id) ON DELETE RESTRICT;
ALTER TABLE inventory_balance ADD CONSTRAINT fk_inventory_balance_material_subtype_id_scope FOREIGN KEY (organization_id,material_subtype_id) REFERENCES material_subtype(organization_id,id) ON DELETE RESTRICT;
CREATE UNIQUE INDEX uq_category_name_scope ON material_category(organization_id,lower(btrim(name))) WHERE organization_id IS NOT NULL;
CREATE UNIQUE INDEX uq_type_name_scope ON material_type(organization_id,category_id,lower(btrim(name))) WHERE organization_id IS NOT NULL;
CREATE UNIQUE INDEX uq_subtype_name_scope ON material_subtype(organization_id,type_id,lower(btrim(name))) WHERE organization_id IS NOT NULL;
CREATE UNIQUE INDEX uq_vehicle_plate_scope ON vehicle(organization_id,upper(license_plate)) WHERE organization_id IS NOT NULL;
CREATE UNIQUE INDEX uq_donor_document_scope ON donor(organization_id,document) WHERE organization_id IS NOT NULL;
CREATE UNIQUE INDEX uq_buyer_document_scope ON buyer(organization_id,document) WHERE organization_id IS NOT NULL AND document IS NOT NULL;
ALTER TABLE input_item ADD CONSTRAINT ck_input_scoped_source CHECK (organization_id IS NULL OR (num_nonnulls(collection_id,donation_id)=1 AND weight_kg>0 AND volume_m3>=0));
ALTER TABLE sorted_item ADD CONSTRAINT ck_sorted_scoped_source CHECK (organization_id IS NULL OR (sorting_id IS NOT NULL AND input_item_id IS NOT NULL AND weight_kg>0 AND volume_m3>=0 AND reject_weight_kg>=0 AND reject_weight_kg<=weight_kg AND reject_volume_m3>=0 AND reject_volume_m3<=volume_m3));
ALTER TABLE pressed_bale ADD CONSTRAINT ck_bale_scoped_source CHECK (organization_id IS NULL OR (pressing_id IS NOT NULL AND sorted_item_id IS NOT NULL AND weight_kg>0 AND initial_volume_m3>final_volume_m3 AND final_volume_m3>=0));
ALTER TABLE sale_item ADD CONSTRAINT ck_sale_item_scoped_parent CHECK (organization_id IS NULL OR (sale_id IS NOT NULL AND weight_kg>0 AND volume_m3>=0 AND unit_price>=0));

-- Collection team links must obey the same scope as other child relationships.
CREATE FUNCTION validate_collection_team_scope() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE collection_scope UUID; member_scope UUID;
BEGIN
 SELECT organization_id INTO collection_scope FROM collection WHERE id=NEW.collection_id;
 SELECT organization_id INTO member_scope FROM team_member WHERE id=NEW.team_member_id;
 IF collection_scope IS DISTINCT FROM member_scope THEN
  RAISE EXCEPTION 'Collection team must belong to the collection organization' USING ERRCODE='23514';
 END IF;
 RETURN NEW;
END;
$$;
CREATE TRIGGER collection_team_scope BEFORE INSERT OR UPDATE ON collection_team
FOR EACH ROW EXECUTE FUNCTION validate_collection_team_scope();
